name: release-solution-to-prod
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment

on:
  workflow_dispatch:

env:
#edit your values here
  BUILD_ENVIRONMENT_URL: https://orgac818224.crm17.dynamics.com
  USERNAME: algattik@oneweekbreathebuild.onmicrosoft.com

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@0.4.0
      with:
        solution-folder: src
        solution-file: out/solutions/Breathe.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
        user-name: ${{env.USERNAME}}
        password-secret: ${{ secrets.password }}
        solution-file: out/solutions/Breathe.zip
        force-overwrite: true
        publish-changes: true

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        user: ${{env.USERNAME}}
        password: ${{ secrets.PASSWORD }}

    - name: 'Test'
      run: az rest --resource ${{env.BUILD_ENVIRONMENT_URL}} --url ${{env.BUILD_ENVIRONMENT_URL}}/api/data/v9.2/WhoAmI

    - name: 'Test query'
      run: az rest --resource ${{env.BUILD_ENVIRONMENT_URL}} --url ${{env.BUILD_ENVIRONMENT_URL}}/api/data/v9.2/WhoAmI

    #TODO further actions, see https://github.com/microsoft/powerplatform-actions-lab/blob/main/sample-workflows/export-and-branch-solution.yml